# Generated by Django 6.0.2 on 2026-02-21 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_exceldownloadrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exceldownloadrequest',
            name='notification_sent',
            field=models.BooleanField(default=False, help_text='Admin xabardor qilindimi'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('excel_request', "Excel So'rovi"), ('excel_approved', 'Excel Tasdiqlandi'), ('excel_rejected', 'Excel Rad Etildi'), ('student_approved', 'Talaba Tasdiqlandi'), ('student_rejected', 'Talaba Rad Etildi'), ('general', 'Umumiy')], default='general', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_object_id', models.IntegerField(blank=True, help_text="Bog'liq obyekt ID (Excel request, Student va h.k.)", null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
