# Generated by Django 6.0.2 on 2026-02-21 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_exceldownloadrequest_notification_sent_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='related_object_id',
            field=models.IntegerField(blank=True, help_text="Bog'liq obyekt ID", null=True),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('target_group', models.CharField(choices=[('all', 'Barcha foydalanuvchilar'), ('super_admin', 'Faqat Super Admin'), ('admin', 'Faqat Admin'), ('operator', 'Faqat Operator')], default='all', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_important', models.BooleanField(default=False, help_text="Muhim e'lon (pop-up)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Muddati', null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-is_important'],
            },
        ),
    ]
