# Generated by Django 6.0.2 on 2026-02-23 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
