# Generated by Django 4.2.30 on 2026-04-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_stickerpack_chatmessage_edited_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='additional_documents',
            field=models.FileField(blank=True, null=True, upload_to='documents/other_documents/'),
        ),
        migrations.AddField(
            model_name='student',
            name='passport_scan',
            field=models.FileField(blank=True, null=True, upload_to='documents/passport_scans/'),
        ),
        migrations.AddField(
            model_name='student',
            name='transcript',
            field=models.FileField(blank=True, null=True, upload_to='documents/transcripts/'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='target_group',
            field=models.CharField(choices=[('all', 'Barcha foydalanuvchilar'), ('super_admin', 'Faqat Super Admin'), ('admin', 'Faqat Admin'), ('operator', 'Faqat Operator'), ('archive', 'Faqat Arxiv')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('operator', "Talaba Qo'shuvchi"), ('archive', 'Arxiv')], default='operator', max_length=20),
        ),
    ]
