# Generated by Django 4.2.30 on 2026-04-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_student_additional_documents_student_passport_scan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hemis_id',
            field=models.CharField(blank=True, help_text='HEMIS tizimidagi identifikator', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('operator', "Talaba Qo'shuvchi"), ('hemis_id_adder', "HEMIS ID Qo'shuvchi"), ('archive', 'Arxiv')], default='operator', max_length=20),
        ),
    ]
