# Generated by Django 4.2.30 on 2026-04-15 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_student_hemis_id_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Tasdiqlagan/Rad etgan admin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('operator', "Talaba Qo'shuvchi"), ('hemis_id_adder', "HEMIS ID Qo'shuvchi"), ('talaba_viewer', "Talabani Ko'ruvchi"), ('archive', 'Arxiv')], default='operator', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='hemis_id',
            field=models.CharField(blank=True, help_text='HEMIS tizimidagi talaba ID raqami', max_length=20, null=True, unique=True),
        ),
    ]
