# Generated by Django 4.2.30 on 2026-04-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_student_approved_by_alter_profile_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(help_text='Sayt logotipi', upload_to='logos/')),
                ('is_active', models.BooleanField(default=True, help_text="Logotip faol yoki yo'qligi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
