# Generated by Django 4.2.30 on 2026-04-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_profile_email_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='roles',
            field=models.JSONField(blank=True, default=list, help_text='Bir nechta rollar'),
        ),
    ]
