# Generated by Django 4.2.30 on 2026-04-20 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_multiple_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Rol nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tashkiliy Rol',
                'verbose_name_plural': 'Tashkiliy Rollar',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='department_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='core.organizationalrole', verbose_name='Tashkiliy Rol'),
        ),
    ]
