# Generated by Django 4.2.30 on 2026-04-20 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_add_organizational_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationalrole',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_roles', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi'),
        ),
    ]
