# Generated by Django 4.2.30 on 2026-04-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_created_by_to_org_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='department_role',
        ),
        migrations.AddField(
            model_name='profile',
            name='organizational_role',
            field=models.CharField(blank=True, choices=[('2', 'Fuqaro'), ('14', "O'quv bo'limi"), ('16', 'Xodim'), ('26', 'Office registration'), ('34', 'Kitobxon'), ('39', 'Hemis monitoring')], max_length=10, null=True, verbose_name='Tashkiliy Rol'),
        ),
        migrations.DeleteModel(
            name='OrganizationalRole',
        ),
    ]
