# Generated by Django 4.2.30 on 2026-04-20 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0018_replace_org_role_with_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('operator', "Talaba Qo'shuvchi"), ('hemis_id_adder', "HEMIS ID Qo'shuvchi"), ('accountant', 'BUxgalter'), ('talaba_viewer', "Talabani Ko'ruvchi"), ('archive', 'Arxiv')], default='operator', max_length=20),
        ),
        migrations.CreateModel(
            name='StudentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="To'lov summasi")),
                ('payment_type', models.CharField(choices=[('tuition', "O'quv to'lovi"), ('contract', 'Shartnoma tolovi'), ('other', 'Boshqa')], default='tuition', max_length=20, verbose_name="To'lov turi")),
                ('payment_date', models.DateField(verbose_name="To'lov sanasi")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kiritdi')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.student', verbose_name='Talaba')),
            ],
            options={
                'verbose_name': "Talaba to'lovi",
                'verbose_name_plural': "Talaba to'lovlari",
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
