# Generated by Django 4.2.30 on 2026-04-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_profile_role_studentpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='contract_amount',
            field=models.DecimalField(decimal_places=0, default=0, help_text="Kontrakt summasi (so'm)", max_digits=12),
        ),
    ]
