# Generated by Django 4.2.30 on 2026-04-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_passwordresetcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email manzili')),
                ('password', models.CharField(max_length=255, verbose_name='Email paroli')),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=255, verbose_name='SMTP server')),
                ('smtp_port', models.IntegerField(default=587, verbose_name='SMTP port')),
                ('use_tls', models.BooleanField(default=True, verbose_name='TLS ishlatish')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email sozlama',
                'verbose_name_plural': 'Email sozlamalari',
            },
        ),
    ]
