# Generated by Django 6.0.4 on 2026-05-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('operator', "Talaba Qo'shuvchi"), ('hemis_id_adder', "HEMIS ID Qo'shuvchi"), ('accountant', 'BUxgalter'), ('talaba_viewer', "Talabani Ko'ruvchi"), ('archive', 'Arxiv'), ('student', 'Talaba (Ariza beruvchi)'), ('employee', 'Xodim (Ariza beruvchi)')], default='operator', max_length=20),
        ),
    ]
