# Generated by Django 6.0.4 on 2026-05-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Buxoro Innovatsiyalar Universiteti', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='HEMIS OTM axborot tizimi', max_length=200)),
                ('about_text', models.TextField(blank=True, help_text='Universitet haqida maʼlumot')),
                ('directions', models.TextField(blank=True, help_text='Yoʻnalishlar yoki asosiy yoʻnalishlar')),
                ('logo', models.ImageField(blank=True, help_text='Kirish sahifasida koʻrsatiladigan logotip', null=True, upload_to='login_page/')),
                ('is_active', models.BooleanField(default=True, help_text='Bu matn va logo faolmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
