# Generated by Django 6.0.4 on 2026-05-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_loginpagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Maksimal 2MB, JPG/PNG', null=True, upload_to='avatars/', verbose_name='Profil rasmi'),
        ),
    ]
