# Generated by Django 6.0.4 on 2026-05-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='landing/news/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube/Vimeo URL')),
                ('link', models.URLField(blank=True, help_text='Batafsil link')),
                ('order', models.IntegerField(default=0, help_text='Tartibi (kichik raqam - birinchi)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Landing Yangilik',
                'verbose_name_plural': 'Landing Yangiliklar',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandingPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default="Ta'lim va taraqqiyot yo'lidamiz", max_length=200)),
                ('hero_subtitle', models.CharField(default='TALABA BOSHQARUV TIZIMI', max_length=200)),
                ('hero_description', models.TextField(default="Zamonaviy ta'lim tizimi orqali talabalarni qabul qilish va boshqaruvni avtomatlashtirish")),
                ('hero_image', models.ImageField(blank=True, help_text='Hero rasm', null=True, upload_to='landing/')),
                ('hero_video', models.FileField(blank=True, help_text='Hero video (MP4)', null=True, upload_to='landing/videos/')),
                ('contact_address', models.CharField(default="Toshkent sh., O'zbekiston", max_length=300)),
                ('contact_phone', models.CharField(default='+998 71 123 45 67', max_length=50)),
                ('contact_email', models.EmailField(default='info@minihemis.uz', max_length=254)),
                ('contact_location_url', models.URLField(blank=True, help_text='Google Maps URL')),
                ('about_title', models.CharField(default='Bizning maqsadimiz', max_length=200)),
                ('about_text', models.TextField(blank=True, default="Universitet haqida ma'lumot")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Landing Page Content',
                'verbose_name_plural': 'Landing Page Contents',
                'ordering': ['-created_at'],
            },
        ),
    ]
