# Generated by Django 4.2.30 on 2026-05-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_landingnews_landingpagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagecontent',
            name='override_applications_count',
            field=models.IntegerField(blank=True, help_text="Arizalar soni (qo'lda sozlash uchun, bo'sh qoldirilsa avtomatik hisoblanadi)", null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='override_faculties_count',
            field=models.IntegerField(blank=True, help_text="Fakultetlar soni (qo'lda sozlash uchun, bo'sh qoldirilsa avtomatik hisoblanadi)", null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='override_specialties_count',
            field=models.IntegerField(blank=True, help_text="Yo'nalishlar soni (qo'lda sozlash uchun, bo'sh qoldirilsa avtomatik hisoblanadi)", null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='override_students_count',
            field=models.IntegerField(blank=True, help_text="Talabalar soni (qo'lda sozlash uchun, bo'sh qoldirilsa avtomatik hisoblanadi)", null=True),
        ),
    ]
