# Generated by Django 4.2.30 on 2026-06-01 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_landingpagecontent_override_applications_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsettings',
            name='password',
        ),
    ]
