# Generated by Django 4.2.30 on 2026-06-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_emailsettings_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email paroli'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('operator', "Talaba Qo'shuvchi"), ('hemis_id_adder', "HEMIS ID Qo'shuvchi"), ('talaba_viewer', "Talabani Ko'ruvchi"), ('student', 'Talaba (Ariza beruvchi)'), ('employee', 'Xodim (Ariza beruvchi)')], default='operator', max_length=20),
        ),
    ]
