# Generated by Django 4.2.30 on 2026-06-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_emailsettings_password_alter_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelImportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_col', models.CharField(default='A', max_length=2, verbose_name='Ism Familiya (F.I.SH) ustuni')),
                ('passport_col', models.CharField(default='B', max_length=2, verbose_name='Pasport ustuni')),
                ('jshshir_col', models.CharField(default='C', max_length=2, verbose_name='JSHSHIR ustuni')),
                ('course_col', models.CharField(default='D', max_length=2, verbose_name='Kurs ustuni')),
                ('phone_col', models.CharField(default='E', max_length=2, verbose_name='Telefon ustuni')),
                ('faculty_col', models.CharField(default='F', max_length=2, verbose_name='Fakultet ustuni')),
                ('specialty_col', models.CharField(default='G', max_length=2, verbose_name='Mutaxassislik ustuni')),
                ('operator_comment_col', models.CharField(default='H', max_length=2, verbose_name='Operator izohi ustuni')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Excel import sozlamasi',
                'verbose_name_plural': 'Excel import sozlamalari',
                'ordering': ['-created_at'],
            },
        ),
    ]
